ap_cruise_speed: 0.09
ap_brake_accel: 0.16
ap_final_yaw: 0.0
ap_goal_tol: 0.010
ap_kp_ang: 1.8
ap_kp_cross: 1.2
ap_max_ang: 0.6
ap_max_lin: 0.11
ap_min_lin: 0.012
ap_turn_factor: 0.25
ap_v_cross_max: 0.08
ap_wp_tol: 0.015
ap_yaw_mode: HOLD_INITIAL
filter_alpha: 0.28
wheel_diameter_mm: 70.0
drive_linear_scale: 0.4940752942
drive_angular_scale: 0.5423793646
default_marker_size_mm: 100.0
ceiling_height_m: 2.1677131734
